<?php

/*
|--------------------------------------------------------------------------
| Idées de repas simples (repli du planificateur, brief §12)
|--------------------------------------------------------------------------
|
| 103 idées de plats courants en Belgique et en France, utilisées par
| PlannerGenerator quand aucune recette compatible n'est trouvée : créées en
| plans « titre seul ». Le vivier doit rester large, sinon la semaine générée
| ramène les mêmes plats tous les deux jours.
|
| Toutes les valeurs nutritionnelles sont des ESTIMATIONS par portion, pas des
| mesures : elles donnent un ordre de grandeur pour choisir un plat proche du
| budget du repas, rien de plus. Les plans issus de ces idées sont d'ailleurs
| toujours marqués `is_estimate` (PlanCalories).
|
| Format : title, calories, proteins, carbs, fat, tags, meal_types, plus
| `ingredients` (ingrédients principaux) et `allergenes` (allergènes usuels de
| la préparation classique — une variante peut en contenir d'autres).
| Ces deux listes passent au filtre de compatibilité : un allergène déclaré au
| profil doit pouvoir être reconnu même quand le titre ne le nomme pas.
|
| tags ⊂ vocabulaire recettes (§5) ; meal_types ⊂ MealType. Un tag de régime
| sert de garant (il court-circuite la recherche de mots-clés) : ne le poser
| que lorsque le plat est réellement compatible.
|
*/

return [
    // --- Petit-déjeuner -------------------------------------------------------------------
    [
        'title' => 'Porridge aux flocons d’avoine, banane et amandes',
        'calories' => 420, 'proteins' => 14, 'carbs' => 62, 'fat' => 12,
        'tags' => ['vegetarien', 'rapide', 'economique'],
        'meal_types' => ['petit_dejeuner'],
        'ingredients' => ['flocons d’avoine', 'lait', 'banane', 'amandes'],
        'allergenes' => ['gluten', 'lait', 'fruits à coque'],
    ],
    [
        'title' => 'Tartines de pain complet, fromage blanc et fruits rouges',
        'calories' => 360, 'proteins' => 18, 'carbs' => 50, 'fat' => 8,
        'tags' => ['vegetarien', 'rapide', 'riche_en_proteines'],
        'meal_types' => ['petit_dejeuner'],
        'ingredients' => ['pain complet', 'fromage blanc', 'fruits rouges'],
        'allergenes' => ['gluten', 'lait'],
    ],
    [
        'title' => 'Œufs brouillés, pain complet et tomate',
        'calories' => 390, 'proteins' => 22, 'carbs' => 30, 'fat' => 18,
        'tags' => ['vegetarien', 'rapide', 'riche_en_proteines', 'sans_lactose'],
        'meal_types' => ['petit_dejeuner'],
        'ingredients' => ['œuf', 'pain complet', 'tomate'],
        'allergenes' => ['œufs', 'gluten'],
    ],
    [
        'title' => 'Yaourt nature, muesli et pomme',
        'calories' => 340, 'proteins' => 13, 'carbs' => 55, 'fat' => 8,
        'tags' => ['vegetarien', 'rapide', 'economique'],
        'meal_types' => ['petit_dejeuner', 'collation'],
        'ingredients' => ['yaourt nature', 'muesli', 'pomme'],
        'allergenes' => ['lait', 'gluten', 'fruits à coque'],
    ],
    [
        'title' => 'Omelette aux épinards et feta',
        'calories' => 380, 'proteins' => 24, 'carbs' => 6, 'fat' => 28,
        'tags' => ['vegetarien', 'keto', 'low_carb', 'sans_gluten', 'rapide'],
        'meal_types' => ['petit_dejeuner', 'diner'],
        'ingredients' => ['œuf', 'épinards', 'feta'],
        'allergenes' => ['œufs', 'lait'],
    ],
    [
        'title' => 'Smoothie banane, lait végétal et beurre de cacahuète',
        'calories' => 350, 'proteins' => 12, 'carbs' => 45, 'fat' => 14,
        'tags' => ['vegan', 'sans_lactose', 'rapide'],
        'meal_types' => ['petit_dejeuner', 'collation'],
        'ingredients' => ['banane', 'boisson à l’avoine', 'beurre de cacahuète'],
        'allergenes' => ['arachides', 'gluten'],
    ],
    [
        'title' => 'Pain complet, beurre de cacahuète et banane',
        'calories' => 430, 'proteins' => 14, 'carbs' => 52, 'fat' => 18,
        'tags' => ['vegan', 'sans_lactose', 'rapide', 'economique'],
        'meal_types' => ['petit_dejeuner'],
        'ingredients' => ['pain complet', 'beurre de cacahuète', 'banane'],
        'allergenes' => ['gluten', 'arachides'],
    ],
    [
        'title' => 'Bol de skyr, granola et myrtilles',
        'calories' => 380, 'proteins' => 26, 'carbs' => 48, 'fat' => 8,
        'tags' => ['vegetarien', 'riche_en_proteines', 'rapide'],
        'meal_types' => ['petit_dejeuner'],
        'ingredients' => ['skyr', 'granola', 'myrtilles'],
        'allergenes' => ['lait', 'gluten', 'fruits à coque'],
    ],
    [
        'title' => 'Pancakes à la banane et à l’avoine',
        'calories' => 410, 'proteins' => 15, 'carbs' => 58, 'fat' => 12,
        'tags' => ['vegetarien', 'economique'],
        'meal_types' => ['petit_dejeuner'],
        'ingredients' => ['flocons d’avoine', 'banane', 'œuf'],
        'allergenes' => ['gluten', 'œufs'],
    ],
    [
        'title' => 'Tartines de pain de seigle, avocat et œuf poché',
        'calories' => 430, 'proteins' => 18, 'carbs' => 38, 'fat' => 23,
        'tags' => ['vegetarien', 'riche_en_proteines', 'sans_lactose'],
        'meal_types' => ['petit_dejeuner'],
        'ingredients' => ['pain de seigle', 'avocat', 'œuf'],
        'allergenes' => ['gluten', 'œufs'],
    ],
    [
        'title' => 'Bircher avoine, pomme râpée et noisettes',
        'calories' => 400, 'proteins' => 12, 'carbs' => 55, 'fat' => 14,
        'tags' => ['vegetarien', 'economique'],
        'meal_types' => ['petit_dejeuner'],
        'ingredients' => ['flocons d’avoine', 'yaourt nature', 'pomme', 'noisettes'],
        'allergenes' => ['gluten', 'lait', 'fruits à coque'],
    ],
    [
        'title' => 'Œufs à la coque et mouillettes',
        'calories' => 350, 'proteins' => 18, 'carbs' => 34, 'fat' => 15,
        'tags' => ['vegetarien', 'rapide', 'economique'],
        'meal_types' => ['petit_dejeuner'],
        'ingredients' => ['œuf', 'pain', 'beurre'],
        'allergenes' => ['œufs', 'gluten', 'lait'],
    ],
    [
        'title' => 'Fromage blanc, graines de chia et mangue',
        'calories' => 320, 'proteins' => 20, 'carbs' => 34, 'fat' => 10,
        'tags' => ['vegetarien', 'riche_en_proteines', 'sans_gluten', 'rapide'],
        'meal_types' => ['petit_dejeuner', 'collation'],
        'ingredients' => ['fromage blanc', 'graines de chia', 'mangue'],
        'allergenes' => ['lait'],
    ],
    [
        'title' => 'Galettes de sarrasin, dinde et emmental',
        'calories' => 450, 'proteins' => 26, 'carbs' => 46, 'fat' => 18,
        'tags' => ['riche_en_proteines', 'halal'],
        'meal_types' => ['petit_dejeuner', 'dejeuner'],
        'ingredients' => ['farine de sarrasin', 'blanc de dinde', 'emmental'],
        'allergenes' => ['œufs', 'lait'],
    ],
    [
        'title' => 'Muesli sans gluten, boisson d’amande et fruits secs',
        'calories' => 390, 'proteins' => 10, 'carbs' => 58, 'fat' => 13,
        'tags' => ['vegan', 'sans_gluten', 'sans_lactose'],
        'meal_types' => ['petit_dejeuner'],
        'ingredients' => ['muesli sans gluten', 'boisson à l’amande', 'abricots secs'],
        'allergenes' => ['fruits à coque', 'sulfites'],
    ],
    [
        'title' => 'Smoothie bowl mangue, épinards et graines de courge',
        'calories' => 360, 'proteins' => 12, 'carbs' => 52, 'fat' => 11,
        'tags' => ['vegan', 'sans_gluten', 'sans_lactose', 'rapide'],
        'meal_types' => ['petit_dejeuner', 'collation'],
        'ingredients' => ['mangue', 'épinards', 'graines de courge', 'banane'],
        'allergenes' => [],
    ],
    [
        'title' => 'Tartine de pain complet, houmous et tomates cerises',
        'calories' => 340, 'proteins' => 12, 'carbs' => 44, 'fat' => 12,
        'tags' => ['vegan', 'sans_lactose', 'rapide', 'economique'],
        'meal_types' => ['petit_dejeuner', 'collation'],
        'ingredients' => ['pain complet', 'houmous', 'tomates cerises'],
        'allergenes' => ['gluten', 'sésame'],
    ],
    [
        'title' => 'Riz au lait aux raisins secs',
        'calories' => 360, 'proteins' => 10, 'carbs' => 62, 'fat' => 8,
        'tags' => ['vegetarien', 'sans_gluten', 'economique'],
        'meal_types' => ['petit_dejeuner', 'collation'],
        'ingredients' => ['riz rond', 'lait', 'raisins secs'],
        'allergenes' => ['lait', 'sulfites'],
    ],

    // Petits-déjeuners copieux : sans eux, un budget matinal de 550 kcal ou plus ne trouvait
    // presque rien dans sa fourchette et ramenait les mêmes trois plats chaque semaine.
    [
        'title' => 'Bol d’avoine complet, beurre d’amande et myrtilles',
        'calories' => 560, 'proteins' => 18, 'carbs' => 68, 'fat' => 22,
        'tags' => ['vegetarien', 'economique'],
        'meal_types' => ['petit_dejeuner'],
        'ingredients' => ['flocons d’avoine', 'lait', 'beurre d’amande', 'myrtilles'],
        'allergenes' => ['gluten', 'lait', 'fruits à coque'],
    ],
    [
        'title' => 'Œufs brouillés, avocat et pain complet',
        'calories' => 600, 'proteins' => 26, 'carbs' => 48, 'fat' => 32,
        'tags' => ['vegetarien', 'riche_en_proteines', 'sans_lactose'],
        'meal_types' => ['petit_dejeuner'],
        'ingredients' => ['œuf', 'avocat', 'pain complet'],
        'allergenes' => ['œufs', 'gluten'],
    ],
    [
        'title' => 'Pain perdu et fruits frais',
        'calories' => 520, 'proteins' => 18, 'carbs' => 66, 'fat' => 19,
        'tags' => ['vegetarien', 'economique'],
        'meal_types' => ['petit_dejeuner'],
        'ingredients' => ['pain rassis', 'œuf', 'lait', 'fraises'],
        'allergenes' => ['gluten', 'œufs', 'lait'],
    ],
    [
        'title' => 'Bagel au fromage frais, saumon fumé et concombre',
        'calories' => 540, 'proteins' => 30, 'carbs' => 56, 'fat' => 21,
        'tags' => ['riche_en_proteines'],
        'meal_types' => ['petit_dejeuner', 'dejeuner'],
        'ingredients' => ['bagel', 'fromage frais', 'saumon fumé', 'concombre'],
        'allergenes' => ['gluten', 'poissons', 'lait'],
    ],
    [
        'title' => 'Porridge protéiné au chocolat noir et banane',
        'calories' => 500, 'proteins' => 26, 'carbs' => 62, 'fat' => 15,
        'tags' => ['vegetarien', 'riche_en_proteines'],
        'meal_types' => ['petit_dejeuner'],
        'ingredients' => ['flocons d’avoine', 'lait', 'chocolat noir', 'banane'],
        'allergenes' => ['gluten', 'lait', 'soja'],
    ],
    [
        'title' => 'Tartines de pain complet, jambon, œuf et fromage',
        'calories' => 560, 'proteins' => 34, 'carbs' => 48, 'fat' => 24,
        'tags' => ['riche_en_proteines'],
        'meal_types' => ['petit_dejeuner'],
        'ingredients' => ['pain complet', 'jambon', 'œuf', 'emmental'],
        'allergenes' => ['gluten', 'œufs', 'lait'],
    ],
    [
        'title' => 'Crêpes au froment, confiture et yaourt',
        'calories' => 480, 'proteins' => 15, 'carbs' => 72, 'fat' => 14,
        'tags' => ['vegetarien', 'economique'],
        'meal_types' => ['petit_dejeuner'],
        'ingredients' => ['farine de froment', 'œuf', 'lait', 'confiture', 'yaourt nature'],
        'allergenes' => ['gluten', 'œufs', 'lait'],
    ],

    // --- Déjeuner --------------------------------------------------------------------------
    [
        'title' => 'Poulet grillé, riz complet et brocolis',
        'calories' => 560, 'proteins' => 42, 'carbs' => 58, 'fat' => 14,
        'tags' => ['riche_en_proteines', 'sans_gluten', 'sans_lactose', 'halal'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['blanc de poulet', 'riz complet', 'brocoli'],
        'allergenes' => [],
    ],
    [
        'title' => 'Salade de lentilles, œuf mollet et légumes croquants',
        'calories' => 480, 'proteins' => 26, 'carbs' => 52, 'fat' => 16,
        'tags' => ['vegetarien', 'economique', 'mediterraneen', 'sans_gluten'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['lentilles', 'œuf', 'carotte', 'concombre'],
        'allergenes' => ['œufs', 'moutarde'],
    ],
    [
        'title' => 'Pâtes complètes à la sauce tomate et thon',
        'calories' => 540, 'proteins' => 32, 'carbs' => 70, 'fat' => 12,
        'tags' => ['rapide', 'economique', 'mediterraneen', 'riche_en_proteines'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['pâtes complètes', 'sauce tomate', 'thon au naturel'],
        'allergenes' => ['gluten', 'poissons'],
    ],
    [
        'title' => 'Bowl de quinoa, pois chiches rôtis et avocat',
        'calories' => 590, 'proteins' => 20, 'carbs' => 66, 'fat' => 24,
        'tags' => ['vegan', 'sans_gluten', 'sans_lactose', 'mediterraneen'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['quinoa', 'pois chiches', 'avocat', 'roquette'],
        'allergenes' => [],
    ],
    [
        'title' => 'Saumon au four, pommes de terre vapeur et haricots verts',
        'calories' => 580, 'proteins' => 36, 'carbs' => 45, 'fat' => 26,
        'tags' => ['mediterraneen', 'dash', 'sans_gluten', 'sans_lactose', 'riche_en_proteines'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['pavé de saumon', 'pommes de terre', 'haricots verts'],
        'allergenes' => ['poissons'],
    ],
    [
        'title' => 'Wrap de dinde, crudités et fromage frais',
        'calories' => 470, 'proteins' => 30, 'carbs' => 44, 'fat' => 16,
        'tags' => ['rapide', 'riche_en_proteines', 'halal'],
        'meal_types' => ['dejeuner'],
        'ingredients' => ['galette de blé', 'blanc de dinde', 'fromage frais', 'salade'],
        'allergenes' => ['gluten', 'lait'],
    ],
    [
        'title' => 'Chili végétarien aux haricots rouges et riz',
        'calories' => 520, 'proteins' => 22, 'carbs' => 80, 'fat' => 10,
        'tags' => ['vegan', 'economique', 'sans_gluten', 'sans_lactose'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['haricots rouges', 'tomate', 'poivron', 'riz'],
        'allergenes' => [],
    ],
    [
        'title' => 'Steak haché 5 %, purée de patate douce et salade verte',
        'calories' => 550, 'proteins' => 38, 'carbs' => 48, 'fat' => 18,
        'tags' => ['riche_en_proteines', 'sans_gluten', 'halal'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['steak haché de bœuf', 'patate douce', 'salade'],
        'allergenes' => ['lait'],
    ],
    [
        'title' => 'Carbonade flamande et pommes de terre vapeur',
        'calories' => 630, 'proteins' => 40, 'carbs' => 58, 'fat' => 25,
        'tags' => ['economique'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['bœuf à braiser', 'bière brune', 'oignon', 'pommes de terre'],
        'allergenes' => ['gluten', 'moutarde', 'sulfites'],
    ],
    [
        'title' => 'Waterzooï de poulet, poireaux et pommes de terre',
        'calories' => 580, 'proteins' => 38, 'carbs' => 48, 'fat' => 24,
        'tags' => ['riche_en_proteines'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['poulet', 'poireau', 'carotte', 'crème', 'pommes de terre'],
        'allergenes' => ['lait', 'céleri'],
    ],
    [
        'title' => 'Chicons au gratin et béchamel',
        'calories' => 520, 'proteins' => 32, 'carbs' => 34, 'fat' => 26,
        'tags' => ['riche_en_proteines'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['chicons', 'jambon', 'béchamel', 'emmental'],
        'allergenes' => ['lait', 'gluten'],
    ],
    [
        'title' => 'Stoemp aux carottes et saucisse grillée',
        'calories' => 620, 'proteins' => 26, 'carbs' => 56, 'fat' => 32,
        'tags' => ['economique'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['pommes de terre', 'carotte', 'saucisse', 'lait'],
        'allergenes' => ['lait', 'gluten', 'sulfites'],
    ],
    [
        'title' => 'Blanquette de veau et riz',
        'calories' => 610, 'proteins' => 38, 'carbs' => 55, 'fat' => 26,
        'tags' => ['riche_en_proteines'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['veau', 'carotte', 'champignons', 'crème', 'riz'],
        'allergenes' => ['lait', 'céleri', 'sulfites'],
    ],
    [
        'title' => 'Hachis Parmentier et salade verte',
        'calories' => 590, 'proteins' => 32, 'carbs' => 52, 'fat' => 28,
        'tags' => ['economique', 'halal'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['bœuf haché', 'pommes de terre', 'lait', 'salade'],
        'allergenes' => ['lait'],
    ],
    [
        'title' => 'Couscous de légumes et pois chiches',
        'calories' => 560, 'proteins' => 20, 'carbs' => 90, 'fat' => 12,
        'tags' => ['vegan', 'sans_lactose', 'economique'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['semoule', 'pois chiches', 'courgette', 'carotte', 'navet'],
        'allergenes' => ['gluten', 'céleri'],
    ],
    [
        'title' => 'Tajine de poulet aux citrons confits et semoule',
        'calories' => 580, 'proteins' => 38, 'carbs' => 62, 'fat' => 18,
        'tags' => ['halal', 'riche_en_proteines'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['poulet', 'citron confit', 'olives', 'semoule'],
        'allergenes' => ['gluten'],
    ],
    [
        'title' => 'Gratin de courgettes au chèvre et boulgour',
        'calories' => 500, 'proteins' => 22, 'carbs' => 52, 'fat' => 21,
        'tags' => ['vegetarien', 'mediterraneen'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['courgette', 'fromage de chèvre', 'boulgour'],
        'allergenes' => ['lait', 'gluten'],
    ],
    [
        'title' => 'Poke bowl saumon, riz et edamame',
        'calories' => 600, 'proteins' => 34, 'carbs' => 66, 'fat' => 20,
        'tags' => ['riche_en_proteines', 'sans_lactose'],
        'meal_types' => ['dejeuner'],
        'ingredients' => ['saumon', 'riz', 'edamame', 'avocat'],
        'allergenes' => ['poissons', 'soja', 'sésame'],
    ],
    [
        'title' => 'Curry de pois chiches, épinards et riz basmati',
        'calories' => 540, 'proteins' => 19, 'carbs' => 78, 'fat' => 15,
        'tags' => ['vegan', 'sans_gluten', 'sans_lactose', 'economique'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['pois chiches', 'épinards', 'lait de coco', 'riz basmati'],
        'allergenes' => [],
    ],
    [
        'title' => 'Lasagnes bolognaises et salade',
        'calories' => 650, 'proteins' => 34, 'carbs' => 62, 'fat' => 28,
        'tags' => [],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['pâtes à lasagne', 'bœuf haché', 'tomate', 'béchamel'],
        'allergenes' => ['gluten', 'lait', 'œufs', 'céleri'],
    ],
    [
        'title' => 'Escalope de dinde panée, purée et haricots verts',
        'calories' => 580, 'proteins' => 40, 'carbs' => 52, 'fat' => 22,
        'tags' => ['riche_en_proteines', 'halal'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['escalope de dinde', 'chapelure', 'pommes de terre', 'haricots verts'],
        'allergenes' => ['gluten', 'œufs', 'lait'],
    ],
    [
        'title' => 'Salade liégeoise aux haricots verts et pommes de terre',
        'calories' => 480, 'proteins' => 16, 'carbs' => 46, 'fat' => 24,
        'tags' => ['economique'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['haricots verts', 'pommes de terre', 'lardons', 'échalote'],
        'allergenes' => ['sulfites'],
    ],
    [
        'title' => 'Quiche lorraine et salade verte',
        'calories' => 560, 'proteins' => 22, 'carbs' => 40, 'fat' => 34,
        'tags' => [],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['pâte brisée', 'lardons', 'œuf', 'crème'],
        'allergenes' => ['gluten', 'œufs', 'lait'],
    ],
    [
        'title' => 'Bœuf sauté aux brocolis et nouilles',
        'calories' => 580, 'proteins' => 36, 'carbs' => 60, 'fat' => 20,
        'tags' => ['riche_en_proteines'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['bœuf', 'brocoli', 'nouilles', 'sauce soja'],
        'allergenes' => ['gluten', 'soja', 'sésame'],
    ],
    [
        'title' => 'Risotto aux champignons et parmesan',
        'calories' => 560, 'proteins' => 18, 'carbs' => 78, 'fat' => 18,
        'tags' => ['vegetarien', 'sans_gluten'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['riz arborio', 'champignons', 'parmesan', 'bouillon de légumes'],
        'allergenes' => ['lait', 'céleri', 'sulfites'],
    ],
    [
        'title' => 'Papillote de colin, fenouil et riz',
        'calories' => 460, 'proteins' => 34, 'carbs' => 50, 'fat' => 13,
        'tags' => ['dash', 'sans_gluten', 'sans_lactose', 'riche_en_proteines'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['colin', 'fenouil', 'riz', 'citron'],
        'allergenes' => ['poissons'],
    ],
    [
        'title' => 'Salade de pâtes complètes, mozzarella et tomates',
        'calories' => 520, 'proteins' => 22, 'carbs' => 64, 'fat' => 19,
        'tags' => ['vegetarien', 'mediterraneen', 'rapide'],
        'meal_types' => ['dejeuner'],
        'ingredients' => ['pâtes complètes', 'mozzarella', 'tomate', 'basilic'],
        'allergenes' => ['gluten', 'lait'],
    ],
    [
        'title' => 'Chili con carne et riz',
        'calories' => 600, 'proteins' => 36, 'carbs' => 68, 'fat' => 18,
        'tags' => ['riche_en_proteines', 'economique', 'sans_gluten', 'sans_lactose', 'halal'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['bœuf haché', 'haricots rouges', 'tomate', 'riz'],
        'allergenes' => [],
    ],
    [
        'title' => 'Galette complète sarrasin, œuf et emmental',
        'calories' => 520, 'proteins' => 26, 'carbs' => 52, 'fat' => 22,
        'tags' => [],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['farine de sarrasin', 'œuf', 'jambon', 'emmental'],
        'allergenes' => ['œufs', 'lait'],
    ],
    [
        'title' => 'Poulet basquaise et riz',
        'calories' => 560, 'proteins' => 40, 'carbs' => 56, 'fat' => 18,
        'tags' => ['halal', 'riche_en_proteines', 'sans_gluten', 'sans_lactose'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['poulet', 'poivron', 'tomate', 'riz'],
        'allergenes' => [],
    ],
    [
        'title' => 'Buddha bowl lentilles, patate douce et tahini',
        'calories' => 560, 'proteins' => 22, 'carbs' => 70, 'fat' => 20,
        'tags' => ['vegan', 'sans_gluten', 'sans_lactose'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['lentilles', 'patate douce', 'tahini', 'chou rouge'],
        'allergenes' => ['sésame'],
    ],
    [
        'title' => 'Moules marinières et frites',
        'calories' => 700, 'proteins' => 34, 'carbs' => 70, 'fat' => 30,
        'tags' => [],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['moules', 'échalote', 'vin blanc', 'frites'],
        'allergenes' => ['mollusques', 'céleri', 'sulfites'],
    ],
    [
        'title' => 'Rôti de porc, chou braisé et pommes de terre',
        'calories' => 620, 'proteins' => 40, 'carbs' => 48, 'fat' => 28,
        'tags' => ['riche_en_proteines'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['rôti de porc', 'chou', 'pommes de terre'],
        'allergenes' => [],
    ],
    [
        'title' => 'Salade de riz, thon, maïs et œuf',
        'calories' => 520, 'proteins' => 30, 'carbs' => 58, 'fat' => 18,
        'tags' => ['rapide', 'economique', 'sans_gluten', 'sans_lactose'],
        'meal_types' => ['dejeuner'],
        'ingredients' => ['riz', 'thon au naturel', 'maïs', 'œuf'],
        'allergenes' => ['poissons', 'œufs', 'moutarde'],
    ],
    [
        'title' => 'Gratin de chou-fleur au jambon',
        'calories' => 480, 'proteins' => 30, 'carbs' => 28, 'fat' => 27,
        'tags' => ['riche_en_proteines'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['chou-fleur', 'jambon', 'béchamel', 'emmental'],
        'allergenes' => ['lait', 'gluten'],
    ],
    [
        'title' => 'Wok de crevettes, légumes croquants et riz',
        'calories' => 520, 'proteins' => 32, 'carbs' => 62, 'fat' => 14,
        'tags' => ['riche_en_proteines', 'sans_lactose'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['crevettes', 'poivron', 'pois gourmands', 'riz', 'sauce soja'],
        'allergenes' => ['crustacés', 'soja', 'gluten', 'sésame'],
    ],

    // Déjeuners copieux : même raison, pour les profils dont le budget de midi dépasse 750 kcal.
    [
        'title' => 'Couscous royal poulet-merguez et semoule',
        'calories' => 820, 'proteins' => 48, 'carbs' => 90, 'fat' => 30,
        'tags' => ['halal', 'riche_en_proteines'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['poulet', 'merguez', 'pois chiches', 'semoule', 'courgette'],
        'allergenes' => ['gluten', 'céleri', 'sulfites'],
    ],
    [
        'title' => 'Pâtes à la carbonara et salade',
        'calories' => 780, 'proteins' => 34, 'carbs' => 88, 'fat' => 30,
        'tags' => [],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['pâtes', 'lardons', 'œuf', 'parmesan'],
        'allergenes' => ['gluten', 'œufs', 'lait'],
    ],
    [
        'title' => 'Burger maison au bœuf, cheddar et frites au four',
        'calories' => 850, 'proteins' => 42, 'carbs' => 84, 'fat' => 38,
        'tags' => ['halal'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['pain à burger', 'steak haché de bœuf', 'cheddar', 'pommes de terre'],
        'allergenes' => ['gluten', 'lait', 'œufs', 'sésame', 'moutarde'],
    ],
    [
        'title' => 'Poulet rôti, frites au four et compote',
        'calories' => 800, 'proteins' => 48, 'carbs' => 80, 'fat' => 32,
        'tags' => ['halal', 'riche_en_proteines', 'sans_gluten', 'sans_lactose'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['cuisse de poulet', 'pommes de terre', 'compote de pomme'],
        'allergenes' => [],
    ],
    [
        'title' => 'Gratin dauphinois et rôti de bœuf',
        'calories' => 780, 'proteins' => 44, 'carbs' => 62, 'fat' => 38,
        'tags' => ['halal', 'riche_en_proteines'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['pommes de terre', 'crème', 'rôti de bœuf'],
        'allergenes' => ['lait'],
    ],
    [
        'title' => 'Curry de bœuf, riz et naan',
        'calories' => 820, 'proteins' => 44, 'carbs' => 94, 'fat' => 28,
        'tags' => ['riche_en_proteines'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['bœuf', 'épices à curry', 'riz', 'naan'],
        'allergenes' => ['gluten', 'lait'],
    ],
    [
        'title' => 'Saumon, pommes de terre rôties et légumes du marché',
        'calories' => 760, 'proteins' => 44, 'carbs' => 62, 'fat' => 34,
        'tags' => ['riche_en_proteines', 'mediterraneen', 'sans_gluten', 'sans_lactose'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['pavé de saumon', 'pommes de terre', 'courgette', 'poivron'],
        'allergenes' => ['poissons'],
    ],
    [
        'title' => 'Lasagnes végétariennes aux légumes et ricotta',
        'calories' => 720, 'proteins' => 30, 'carbs' => 76, 'fat' => 30,
        'tags' => ['vegetarien'],
        'meal_types' => ['dejeuner', 'diner'],
        'ingredients' => ['pâtes à lasagne', 'ricotta', 'aubergine', 'courgette', 'tomate'],
        'allergenes' => ['gluten', 'lait', 'œufs'],
    ],

    // --- Dîner -----------------------------------------------------------------------------
    [
        'title' => 'Soupe de légumes maison et tartine de chèvre',
        'calories' => 380, 'proteins' => 14, 'carbs' => 42, 'fat' => 16,
        'tags' => ['vegetarien', 'economique', 'dash'],
        'meal_types' => ['diner'],
        'ingredients' => ['poireau', 'carotte', 'pomme de terre', 'pain', 'fromage de chèvre'],
        'allergenes' => ['gluten', 'lait', 'céleri'],
    ],
    [
        'title' => 'Poêlée de tofu, légumes sautés et nouilles de riz',
        'calories' => 500, 'proteins' => 24, 'carbs' => 60, 'fat' => 16,
        'tags' => ['vegan', 'sans_lactose', 'sans_gluten', 'rapide'],
        'meal_types' => ['diner', 'dejeuner'],
        'ingredients' => ['tofu', 'brocoli', 'carotte', 'nouilles de riz', 'tamari'],
        'allergenes' => ['soja', 'sésame'],
    ],
    [
        'title' => 'Cabillaud en papillote, courgettes et boulgour',
        'calories' => 450, 'proteins' => 34, 'carbs' => 46, 'fat' => 10,
        'tags' => ['mediterraneen', 'dash', 'sans_lactose', 'riche_en_proteines'],
        'meal_types' => ['diner', 'dejeuner'],
        'ingredients' => ['cabillaud', 'courgette', 'boulgour', 'citron'],
        'allergenes' => ['poissons', 'gluten'],
    ],
    [
        'title' => 'Ratatouille et œufs au plat',
        'calories' => 400, 'proteins' => 18, 'carbs' => 24, 'fat' => 24,
        'tags' => ['vegetarien', 'mediterraneen', 'low_carb', 'sans_gluten', 'sans_lactose'],
        'meal_types' => ['diner'],
        'ingredients' => ['aubergine', 'courgette', 'poivron', 'tomate', 'œuf'],
        'allergenes' => ['œufs'],
    ],
    [
        'title' => 'Salade César légère au poulet',
        'calories' => 430, 'proteins' => 34, 'carbs' => 18, 'fat' => 24,
        'tags' => ['low_carb', 'riche_en_proteines', 'rapide', 'halal'],
        'meal_types' => ['diner', 'dejeuner'],
        'ingredients' => ['blanc de poulet', 'laitue romaine', 'parmesan', 'sauce légère'],
        'allergenes' => ['œufs', 'lait', 'gluten', 'moutarde'],
    ],
    [
        'title' => 'Dahl de lentilles corail au lait de coco et riz basmati',
        'calories' => 520, 'proteins' => 20, 'carbs' => 74, 'fat' => 14,
        'tags' => ['vegan', 'sans_gluten', 'sans_lactose', 'economique'],
        'meal_types' => ['diner', 'dejeuner'],
        'ingredients' => ['lentilles corail', 'lait de coco', 'riz basmati', 'épices'],
        'allergenes' => [],
    ],
    [
        'title' => 'Soupe de potiron et tartine de pain complet',
        'calories' => 360, 'proteins' => 11, 'carbs' => 50, 'fat' => 12,
        'tags' => ['vegetarien', 'economique', 'dash'],
        'meal_types' => ['diner'],
        'ingredients' => ['potiron', 'oignon', 'crème', 'pain complet'],
        'allergenes' => ['lait', 'gluten'],
    ],
    [
        'title' => 'Velouté de poireaux, pommes de terre et œuf dur',
        'calories' => 380, 'proteins' => 16, 'carbs' => 44, 'fat' => 15,
        'tags' => ['vegetarien', 'economique', 'sans_gluten'],
        'meal_types' => ['diner'],
        'ingredients' => ['poireau', 'pomme de terre', 'lait', 'œuf'],
        'allergenes' => ['lait', 'œufs', 'céleri'],
    ],
    [
        'title' => 'Omelette aux champignons et salade verte',
        'calories' => 380, 'proteins' => 24, 'carbs' => 8, 'fat' => 28,
        'tags' => ['vegetarien', 'low_carb', 'sans_gluten', 'rapide', 'riche_en_proteines'],
        'meal_types' => ['diner'],
        'ingredients' => ['œuf', 'champignons', 'salade', 'beurre'],
        'allergenes' => ['œufs', 'lait'],
    ],
    [
        'title' => 'Poisson blanc vapeur, épinards et quinoa',
        'calories' => 440, 'proteins' => 34, 'carbs' => 42, 'fat' => 13,
        'tags' => ['dash', 'sans_gluten', 'sans_lactose', 'riche_en_proteines'],
        'meal_types' => ['diner', 'dejeuner'],
        'ingredients' => ['filet de poisson blanc', 'épinards', 'quinoa'],
        'allergenes' => ['poissons'],
    ],
    [
        'title' => 'Tartiflette allégée et salade',
        'calories' => 620, 'proteins' => 26, 'carbs' => 48, 'fat' => 34,
        'tags' => [],
        'meal_types' => ['diner'],
        'ingredients' => ['pommes de terre', 'reblochon', 'lardons', 'oignon'],
        'allergenes' => ['lait', 'sulfites'],
    ],
    [
        'title' => 'Pizza maison aux légumes grillés',
        'calories' => 560, 'proteins' => 22, 'carbs' => 70, 'fat' => 20,
        'tags' => ['vegetarien'],
        'meal_types' => ['diner'],
        'ingredients' => ['pâte à pizza', 'tomate', 'courgette', 'poivron', 'mozzarella'],
        'allergenes' => ['gluten', 'lait'],
    ],
    [
        'title' => 'Curry thaï de tofu et riz jasmin',
        'calories' => 520, 'proteins' => 22, 'carbs' => 62, 'fat' => 20,
        'tags' => ['vegan', 'sans_lactose', 'sans_gluten'],
        'meal_types' => ['diner', 'dejeuner'],
        'ingredients' => ['tofu', 'lait de coco', 'pâte de curry', 'riz jasmin'],
        'allergenes' => ['soja'],
    ],
    [
        'title' => 'Gratin de pâtes aux légumes et ricotta',
        'calories' => 540, 'proteins' => 22, 'carbs' => 66, 'fat' => 20,
        'tags' => ['vegetarien'],
        'meal_types' => ['diner', 'dejeuner'],
        'ingredients' => ['pâtes', 'ricotta', 'épinards', 'tomate'],
        'allergenes' => ['gluten', 'lait'],
    ],
    [
        'title' => 'Salade tiède de pommes de terre, hareng et aneth',
        'calories' => 430, 'proteins' => 24, 'carbs' => 38, 'fat' => 20,
        'tags' => ['sans_gluten', 'sans_lactose'],
        'meal_types' => ['diner', 'dejeuner'],
        'ingredients' => ['pommes de terre', 'filets de hareng', 'aneth', 'oignon rouge'],
        'allergenes' => ['poissons', 'moutarde'],
    ],
    [
        'title' => 'Boulettes de bœuf sauce tomate et purée',
        'calories' => 560, 'proteins' => 34, 'carbs' => 50, 'fat' => 24,
        'tags' => ['halal', 'riche_en_proteines'],
        'meal_types' => ['diner', 'dejeuner'],
        'ingredients' => ['bœuf haché', 'sauce tomate', 'pommes de terre', 'lait'],
        'allergenes' => ['gluten', 'œufs', 'lait'],
    ],
    [
        'title' => 'Tarte aux légumes et salade verte',
        'calories' => 480, 'proteins' => 16, 'carbs' => 48, 'fat' => 24,
        'tags' => ['vegetarien'],
        'meal_types' => ['diner'],
        'ingredients' => ['pâte brisée', 'courgette', 'tomate', 'œuf', 'crème'],
        'allergenes' => ['gluten', 'œufs', 'lait'],
    ],
    [
        'title' => 'Bouillon de nouilles au poulet et légumes',
        'calories' => 460, 'proteins' => 32, 'carbs' => 54, 'fat' => 12,
        'tags' => ['rapide', 'halal', 'riche_en_proteines'],
        'meal_types' => ['diner'],
        'ingredients' => ['nouilles', 'blanc de poulet', 'bouillon', 'pak choï'],
        'allergenes' => ['gluten', 'œufs', 'soja', 'céleri'],
    ],
    [
        'title' => 'Croque-monsieur au pain complet et soupe de tomates',
        'calories' => 520, 'proteins' => 26, 'carbs' => 50, 'fat' => 24,
        'tags' => [],
        'meal_types' => ['diner'],
        'ingredients' => ['pain complet', 'jambon', 'emmental', 'soupe de tomates'],
        'allergenes' => ['gluten', 'lait'],
    ],
    [
        'title' => 'Aubergines farcies au quinoa et à la feta',
        'calories' => 470, 'proteins' => 18, 'carbs' => 48, 'fat' => 22,
        'tags' => ['vegetarien', 'mediterraneen', 'sans_gluten'],
        'meal_types' => ['diner', 'dejeuner'],
        'ingredients' => ['aubergine', 'quinoa', 'feta', 'tomate'],
        'allergenes' => ['lait'],
    ],
    [
        'title' => 'Poêlée de chou kale, pois chiches et patate douce',
        'calories' => 440, 'proteins' => 16, 'carbs' => 58, 'fat' => 15,
        'tags' => ['vegan', 'sans_gluten', 'sans_lactose', 'economique'],
        'meal_types' => ['diner', 'dejeuner'],
        'ingredients' => ['chou kale', 'pois chiches', 'patate douce', 'huile d’olive'],
        'allergenes' => [],
    ],
    [
        'title' => 'Cabillaud, ratatouille et polenta',
        'calories' => 480, 'proteins' => 34, 'carbs' => 44, 'fat' => 16,
        'tags' => ['mediterraneen', 'dash', 'sans_gluten', 'sans_lactose'],
        'meal_types' => ['diner', 'dejeuner'],
        'ingredients' => ['cabillaud', 'aubergine', 'courgette', 'polenta'],
        'allergenes' => ['poissons'],
    ],

    // --- Collation -------------------------------------------------------------------------
    [
        'title' => 'Pomme et poignée d’amandes',
        'calories' => 240, 'proteins' => 6, 'carbs' => 28, 'fat' => 14,
        'tags' => ['vegan', 'sans_gluten', 'sans_lactose', 'rapide', 'economique'],
        'meal_types' => ['collation'],
        'ingredients' => ['pomme', 'amandes'],
        'allergenes' => ['fruits à coque'],
    ],
    [
        'title' => 'Fromage blanc, miel et noix',
        'calories' => 250, 'proteins' => 16, 'carbs' => 22, 'fat' => 10,
        'tags' => ['vegetarien', 'riche_en_proteines', 'rapide'],
        'meal_types' => ['collation'],
        'ingredients' => ['fromage blanc', 'miel', 'noix'],
        'allergenes' => ['lait', 'fruits à coque'],
    ],
    [
        'title' => 'Houmous et bâtonnets de carotte',
        'calories' => 220, 'proteins' => 8, 'carbs' => 24, 'fat' => 10,
        'tags' => ['vegan', 'sans_gluten', 'sans_lactose', 'mediterraneen', 'rapide'],
        'meal_types' => ['collation'],
        'ingredients' => ['pois chiches', 'tahini', 'carotte'],
        'allergenes' => ['sésame'],
    ],
    [
        'title' => 'Banane et carré de chocolat noir',
        'calories' => 180, 'proteins' => 3, 'carbs' => 32, 'fat' => 5,
        'tags' => ['vegan', 'sans_gluten', 'sans_lactose', 'rapide', 'economique'],
        'meal_types' => ['collation'],
        'ingredients' => ['banane', 'chocolat noir'],
        'allergenes' => ['soja'],
    ],
    [
        'title' => 'Poignée de noix et clémentines',
        'calories' => 220, 'proteins' => 5, 'carbs' => 20, 'fat' => 14,
        'tags' => ['vegan', 'sans_gluten', 'sans_lactose', 'rapide'],
        'meal_types' => ['collation'],
        'ingredients' => ['noix', 'clémentine'],
        'allergenes' => ['fruits à coque'],
    ],
    [
        'title' => 'Skyr nature et framboises',
        'calories' => 150, 'proteins' => 18, 'carbs' => 14, 'fat' => 1,
        'tags' => ['vegetarien', 'riche_en_proteines', 'sans_gluten', 'rapide'],
        'meal_types' => ['collation'],
        'ingredients' => ['skyr', 'framboises'],
        'allergenes' => ['lait'],
    ],
    [
        'title' => 'Tranche de pain d’épices',
        'calories' => 160, 'proteins' => 3, 'carbs' => 32, 'fat' => 3,
        'tags' => ['vegetarien', 'economique'],
        'meal_types' => ['collation'],
        'ingredients' => ['farine de seigle', 'miel', 'épices'],
        'allergenes' => ['gluten', 'œufs', 'lait'],
    ],
    [
        'title' => 'Œuf dur et bâtonnets de concombre',
        'calories' => 110, 'proteins' => 9, 'carbs' => 3, 'fat' => 7,
        'tags' => ['vegetarien', 'low_carb', 'sans_gluten', 'sans_lactose', 'riche_en_proteines'],
        'meal_types' => ['collation'],
        'ingredients' => ['œuf', 'concombre'],
        'allergenes' => ['œufs'],
    ],
    [
        'title' => 'Barre maison avoine, dattes et amandes',
        'calories' => 210, 'proteins' => 5, 'carbs' => 30, 'fat' => 8,
        'tags' => ['vegan', 'sans_lactose', 'economique'],
        'meal_types' => ['collation'],
        'ingredients' => ['flocons d’avoine', 'dattes', 'amandes'],
        'allergenes' => ['gluten', 'fruits à coque'],
    ],
    [
        'title' => 'Compote sans sucre ajouté et flocons d’avoine',
        'calories' => 180, 'proteins' => 4, 'carbs' => 36, 'fat' => 2,
        'tags' => ['vegan', 'sans_lactose', 'economique'],
        'meal_types' => ['collation'],
        'ingredients' => ['compote de pomme', 'flocons d’avoine'],
        'allergenes' => ['gluten'],
    ],
    [
        'title' => 'Bâtonnets de céleri et fromage frais',
        'calories' => 130, 'proteins' => 7, 'carbs' => 8, 'fat' => 8,
        'tags' => ['vegetarien', 'low_carb', 'sans_gluten', 'rapide'],
        'meal_types' => ['collation'],
        'ingredients' => ['céleri branche', 'fromage frais'],
        'allergenes' => ['lait', 'céleri'],
    ],
    [
        'title' => 'Amandes et carré de chocolat noir',
        'calories' => 230, 'proteins' => 7, 'carbs' => 16, 'fat' => 16,
        'tags' => ['vegan', 'sans_gluten', 'sans_lactose', 'rapide'],
        'meal_types' => ['collation'],
        'ingredients' => ['amandes', 'chocolat noir'],
        'allergenes' => ['fruits à coque', 'soja'],
    ],
];
