name: mavioh
description: "Mavi'oh — coach nutrition & sport."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  flutter_secure_storage: ^10.0.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  mobile_scanner: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: assets/app_icon/favicon.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/logoMoh.png
