<?php

namespace Database\Seeders;

use App\Models\Exercise;
use Illuminate\Database\Seeder;

/**
 * Catalogue public des exercices (≥ 70). Idempotent : upsert par slug.
 *
 * Vocabulaire (brief §13.1) :
 * - category : force | cardio | mobilite | gainage
 * - muscle_group : jambes | fessiers | dos | pectoraux | epaules | bras | abdos | corps_entier | cardio | mobilite
 * - equipment : aucun | halteres | barre | kettlebell | elastiques | banc | barre_traction | machine | tapis | velo
 * - level : debutant | intermediaire | avance
 * - contraindications ⊂ genoux, dos, epaules, poignets, hanches, cou, chevilles, coudes
 */
class ExerciseSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $rows = collect(self::catalog())->map(function (array $e) use ($now) {
            return [
                'name' => $e['name'],
                'slug' => $e['slug'],
                'category' => $e['category'],
                'muscle_group' => $e['muscle_group'],
                'equipment' => $e['equipment'],
                'level' => $e['level'],
                'met' => $e['met'],
                'default_sets' => $e['sets'],
                'default_reps' => $e['reps'],
                'default_duration_sec' => $e['duration_sec'],
                'instructions' => $e['instructions'],
                'contraindications' => json_encode($e['contraindications'], JSON_UNESCAPED_UNICODE),
                'is_public' => true,
                'created_by_user_id' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        });

        $rows->chunk(25)->each(function ($chunk) {
            Exercise::upsert(
                $chunk->values()->all(),
                ['slug'],
                [
                    'name', 'category', 'muscle_group', 'equipment', 'level', 'met',
                    'default_sets', 'default_reps', 'default_duration_sec', 'instructions',
                    'contraindications', 'is_public', 'updated_at',
                ],
            );
        });

        $this->command?->info('Exercices : '.$rows->count().' entrées synchronisées.');
    }

    /**
     * Construit une ligne du catalogue.
     *
     * @param  list<string>  $contra
     */
    private static function ex(
        string $name,
        string $slug,
        string $category,
        string $muscle,
        string $equipment,
        string $level,
        float $met,
        ?int $sets,
        ?int $reps,
        ?int $durationSec,
        string $instructions,
        array $contra = [],
    ): array {
        return [
            'name' => $name,
            'slug' => $slug,
            'category' => $category,
            'muscle_group' => $muscle,
            'equipment' => $equipment,
            'level' => $level,
            'met' => $met,
            'sets' => $sets,
            'reps' => $reps,
            'duration_sec' => $durationSec,
            'instructions' => $instructions,
            'contraindications' => array_values($contra),
        ];
    }

    /**
     * @return list<array<string, mixed>>
     */
    public static function catalog(): array
    {
        return [
            // ------------------------------------------------------------------
            // FORCE — sans matériel
            // ------------------------------------------------------------------
            self::ex('Squat au poids du corps', 'squat-poids-du-corps', 'force', 'jambes', 'aucun', 'debutant', 5.0, 3, 12, null,
                'Pieds largeur d’épaules, descends en poussant les fesses vers l’arrière, genoux dans l’axe des pieds. Remonte en poussant dans les talons, dos droit.',
                ['genoux', 'hanches']),
            self::ex('Squat sumo', 'squat-sumo', 'force', 'fessiers', 'aucun', 'debutant', 5.0, 3, 12, null,
                'Pieds très écartés, pointes vers l’extérieur. Descends en gardant le buste droit, puis remonte en serrant les fessiers.',
                ['genoux', 'hanches']),
            self::ex('Fentes avant', 'fentes-avant', 'force', 'jambes', 'aucun', 'debutant', 4.5, 3, 10, null,
                'Fais un grand pas en avant et fléchis les deux genoux à 90°, le genou arrière proche du sol. Reviens en poussant sur la jambe avant.',
                ['genoux', 'hanches']),
            self::ex('Fentes arrière', 'fentes-arriere', 'force', 'fessiers', 'aucun', 'debutant', 4.5, 3, 10, null,
                'Recule un pied et descends jusqu’à ce que le genou arrière frôle le sol. Reviens en poussant sur le talon avant, buste droit.',
                ['genoux', 'hanches']),
            self::ex('Fentes bulgares', 'fentes-bulgares', 'force', 'fessiers', 'aucun', 'intermediaire', 5.0, 3, 10, null,
                'Un pied surélevé derrière toi sur une marche ou une chaise, descends sur la jambe avant en contrôlant. Remonte sans verrouiller le genou.',
                ['genoux', 'hanches']),
            self::ex('Chaise contre le mur', 'chaise-murale', 'force', 'jambes', 'aucun', 'debutant', 3.0, 3, null, 40,
                'Dos plaqué au mur, glisse jusqu’à avoir les cuisses parallèles au sol. Tiens la position en respirant calmement.',
                ['genoux']),
            self::ex('Pistol squat assisté', 'pistol-squat-assiste', 'force', 'jambes', 'aucun', 'avance', 6.0, 3, 6, null,
                'Tiens-toi à un support, lève une jambe devant toi et descends sur l’autre jambe le plus bas possible. Remonte en poussant dans le talon.',
                ['genoux', 'chevilles', 'hanches']),
            self::ex('Mollets debout', 'mollets-debout', 'force', 'jambes', 'aucun', 'debutant', 3.0, 3, 20, null,
                'Debout, monte sur la pointe des pieds le plus haut possible puis redescends lentement. Tiens-toi à un mur si besoin.',
                ['chevilles']),
            self::ex('Pont fessier', 'pont-fessier', 'force', 'fessiers', 'aucun', 'debutant', 3.0, 3, 15, null,
                'Allongé sur le dos, pieds à plat, soulève le bassin en serrant les fessiers jusqu’à aligner épaules, hanches et genoux. Redescends sans toucher le sol.',
                ['cou']),
            self::ex('Pont fessier unilatéral', 'pont-fessier-unilateral', 'force', 'fessiers', 'aucun', 'intermediaire', 3.5, 3, 10, null,
                'Même position que le pont fessier, mais une jambe tendue en l’air. Pousse dans le talon au sol pour monter le bassin sans le laisser basculer.',
                ['cou']),
            self::ex('Pompes', 'pompes', 'force', 'pectoraux', 'aucun', 'debutant', 4.0, 3, 10, null,
                'Mains sous les épaules, corps aligné de la tête aux talons. Descends la poitrine vers le sol en gardant les coudes à 45°, puis pousse.',
                ['epaules', 'poignets']),
            self::ex('Pompes sur les genoux', 'pompes-genoux', 'force', 'pectoraux', 'aucun', 'debutant', 3.5, 3, 10, null,
                'Genoux au sol, mains sous les épaules, gaine le ventre. Descends la poitrine vers le sol puis remonte en poussant fort.',
                ['epaules', 'poignets', 'genoux']),
            self::ex('Pompes déclinées', 'pompes-declinees', 'force', 'pectoraux', 'aucun', 'intermediaire', 4.5, 3, 10, null,
                'Pieds surélevés sur une marche, mains au sol. Descends en contrôlant, la tête dans l’axe, puis pousse jusqu’à tendre les bras.',
                ['epaules', 'poignets']),
            self::ex('Pompes diamant', 'pompes-diamant', 'force', 'bras', 'aucun', 'avance', 5.0, 3, 8, null,
                'Mains jointes sous la poitrine en forme de losange. Descends coudes serrés le long du corps puis pousse : les triceps travaillent fort.',
                ['epaules', 'poignets', 'coudes']),
            self::ex('Dips sur chaise', 'dips-chaise', 'force', 'bras', 'aucun', 'intermediaire', 4.5, 3, 10, null,
                'Mains au bord d’une chaise stable derrière toi, jambes tendues devant. Fléchis les coudes pour descendre les fesses puis pousse.',
                ['epaules', 'coudes', 'poignets']),
            self::ex('Superman', 'superman', 'force', 'dos', 'aucun', 'debutant', 3.0, 3, 12, null,
                'Allongé sur le ventre, décolle simultanément bras et jambes de quelques centimètres en regardant le sol. Tiens une seconde puis relâche.',
                ['dos']),
            self::ex('Crunch', 'crunch', 'force', 'abdos', 'aucun', 'debutant', 3.0, 3, 15, null,
                'Sur le dos, genoux fléchis, décolle les épaules du sol en enroulant le haut du dos, menton légèrement rentré. Redescends lentement.',
                ['cou', 'dos']),
            self::ex('Crunch bicyclette', 'crunch-bicyclette', 'force', 'abdos', 'aucun', 'intermediaire', 4.0, 3, 20, null,
                'Sur le dos, mains aux tempes, amène le coude vers le genou opposé en alternant, comme un pédalage. Garde le bas du dos au sol.',
                ['cou', 'dos']),
            self::ex('Relevé de jambes allongé', 'releve-de-jambes', 'force', 'abdos', 'aucun', 'intermediaire', 3.5, 3, 12, null,
                'Sur le dos, jambes tendues, monte-les à la verticale puis redescends sans toucher le sol. Plaque le bas du dos au tapis.',
                ['dos', 'cou']),
            self::ex('Squat sauté', 'squat-saute', 'cardio', 'jambes', 'aucun', 'intermediaire', 8.0, 3, 10, null,
                'Descends en squat puis explose vers le haut. Amortis l’atterrissage sur l’avant des pieds en refléchissant les genoux.',
                ['genoux', 'chevilles', 'hanches']),
            self::ex('Fentes sautées', 'fentes-sautees', 'cardio', 'jambes', 'aucun', 'avance', 9.0, 3, 10, null,
                'En position de fente, saute et change de jambe en l’air pour atterrir en fente inversée. Amortis chaque réception.',
                ['genoux', 'chevilles', 'hanches']),

            // ------------------------------------------------------------------
            // FORCE — banc, haltères, barre, kettlebell
            // ------------------------------------------------------------------
            self::ex('Step-up sur banc', 'step-up-banc', 'force', 'jambes', 'banc', 'debutant', 5.0, 3, 12, null,
                'Pose un pied entier sur le banc et monte en poussant dans le talon, sans t’aider de la jambe arrière. Redescends en contrôlant.',
                ['genoux']),
            self::ex('Hip thrust au banc', 'hip-thrust-banc', 'force', 'fessiers', 'banc', 'intermediaire', 4.0, 3, 12, null,
                'Haut du dos appuyé sur le banc, pieds au sol, pousse le bassin vers le haut jusqu’à l’horizontale en serrant les fessiers. Menton rentré.',
                ['hanches']),
            self::ex('Développé couché haltères', 'developpe-couche-halteres', 'force', 'pectoraux', 'halteres', 'intermediaire', 5.0, 3, 10, null,
                'Allongé sur le banc, haltères au niveau de la poitrine, pousse vers le haut jusqu’à tendre les bras puis redescends lentement.',
                ['epaules']),
            self::ex('Développé incliné haltères', 'developpe-incline-halteres', 'force', 'pectoraux', 'halteres', 'intermediaire', 5.0, 3, 10, null,
                'Banc incliné à 30–45°, pousse les haltères vers le haut en gardant les poignets au-dessus des coudes. Redescends jusqu’à la poitrine.',
                ['epaules']),
            self::ex('Écarté couché haltères', 'ecarte-couche-halteres', 'force', 'pectoraux', 'halteres', 'intermediaire', 4.0, 3, 12, null,
                'Bras presque tendus au-dessus de la poitrine, ouvre-les sur les côtés en arc de cercle sans descendre sous le niveau des épaules, puis referme.',
                ['epaules']),
            self::ex('Développé couché barre', 'developpe-couche-barre', 'force', 'pectoraux', 'barre', 'avance', 6.0, 4, 6, null,
                'Barre saisie un peu plus large que les épaules, descends-la vers le bas de la poitrine en contrôlant, puis pousse. Omoplates serrées, pieds ancrés.',
                ['epaules', 'poignets']),
            self::ex('Développé militaire haltères', 'developpe-militaire-halteres', 'force', 'epaules', 'halteres', 'intermediaire', 5.0, 3, 10, null,
                'Assis ou debout, haltères au niveau des oreilles, pousse au-dessus de la tête sans cambrer. Redescends jusqu’aux épaules.',
                ['epaules', 'cou']),
            self::ex('Développé militaire barre', 'developpe-militaire-barre', 'force', 'epaules', 'barre', 'avance', 6.0, 4, 6, null,
                'Debout, barre au niveau des clavicules, gaine fort et pousse la barre au-dessus de la tête en passant près du visage. Redescends lentement.',
                ['epaules', 'dos', 'cou']),
            self::ex('Élévations latérales', 'elevations-laterales', 'force', 'epaules', 'halteres', 'debutant', 3.5, 3, 12, null,
                'Haltères le long du corps, monte les bras sur les côtés jusqu’à l’horizontale, coudes légèrement fléchis. Redescends sans balancer.',
                ['epaules']),
            self::ex('Élévations frontales', 'elevations-frontales', 'force', 'epaules', 'halteres', 'debutant', 3.5, 3, 12, null,
                'Haltères devant les cuisses, monte-les devant toi jusqu’à la hauteur des yeux en alternant ou ensemble. Contrôle la descente.',
                ['epaules']),
            self::ex('Oiseau haltères', 'oiseau-halteres', 'force', 'epaules', 'halteres', 'intermediaire', 4.0, 3, 12, null,
                'Buste penché vers l’avant, dos plat, ouvre les bras sur les côtés en serrant les omoplates. Haltères légers, mouvement contrôlé.',
                ['epaules', 'dos']),
            self::ex('Curl biceps haltères', 'curl-biceps-halteres', 'force', 'bras', 'halteres', 'debutant', 3.5, 3, 12, null,
                'Coudes collés au corps, monte les haltères vers les épaules en tournant les paumes vers toi. Redescends lentement sans balancer.',
                ['coudes']),
            self::ex('Curl marteau', 'curl-marteau', 'force', 'bras', 'halteres', 'debutant', 3.5, 3, 12, null,
                'Paumes face à face comme si tu tenais un marteau, fléchis les coudes pour monter les haltères. Poignets neutres, coudes fixes.',
                ['coudes', 'poignets']),
            self::ex('Curl biceps barre', 'curl-biceps-barre', 'force', 'bras', 'barre', 'intermediaire', 4.0, 3, 10, null,
                'Barre en prise supination, coudes près du corps, monte la barre vers la poitrine puis redescends en contrôlant. Ne cambre pas.',
                ['coudes', 'poignets']),
            self::ex('Extension triceps nuque', 'extension-triceps-nuque', 'force', 'bras', 'halteres', 'intermediaire', 4.0, 3, 12, null,
                'Un haltère tenu à deux mains au-dessus de la tête, fléchis les coudes pour descendre derrière la nuque puis tends les bras.',
                ['coudes', 'epaules']),
            self::ex('Kickback triceps', 'kickback-triceps', 'force', 'bras', 'halteres', 'debutant', 3.5, 3, 12, null,
                'Buste penché, coude fixé le long du corps, tends l’avant-bras vers l’arrière jusqu’à aligner le bras. Reviens lentement.',
                ['coudes']),
            self::ex('Rowing haltère un bras', 'rowing-haltere-un-bras', 'force', 'dos', 'halteres', 'debutant', 4.5, 3, 12, null,
                'Une main en appui sur un banc, tire l’haltère vers la hanche en gardant le dos plat et le coude près du corps. Redescends lentement.',
                ['dos']),
            self::ex('Rowing barre', 'rowing-barre', 'force', 'dos', 'barre', 'avance', 6.0, 4, 8, null,
                'Buste penché à 45°, dos plat, tire la barre vers le bas du ventre en serrant les omoplates. Redescends sans arrondir le dos.',
                ['dos']),
            self::ex('Soulevé de terre barre', 'souleve-de-terre-barre', 'force', 'corps_entier', 'barre', 'avance', 6.0, 4, 5, null,
                'Barre contre les tibias, dos plat, pousse le sol avec les jambes et redresse-toi en gardant la barre proche du corps. Verrouille les hanches en haut.',
                ['dos', 'hanches']),
            self::ex('Soulevé de terre roumain haltères', 'souleve-de-terre-roumain-halteres', 'force', 'fessiers', 'halteres', 'intermediaire', 5.0, 3, 10, null,
                'Debout, haltères devant les cuisses, pousse les fesses en arrière en gardant les jambes presque tendues et le dos plat. Reviens en serrant les fessiers.',
                ['dos', 'hanches']),
            self::ex('Squat barre', 'squat-barre', 'force', 'jambes', 'barre', 'avance', 6.0, 4, 6, null,
                'Barre sur le haut du dos, pieds largeur d’épaules, descends en contrôlant jusqu’à ce que les cuisses soient parallèles au sol. Remonte dos gainé.',
                ['genoux', 'dos', 'hanches']),
            self::ex('Goblet squat', 'goblet-squat', 'force', 'jambes', 'kettlebell', 'debutant', 5.0, 3, 12, null,
                'Kettlebell tenue contre la poitrine, descends en squat en gardant le buste droit et les coudes entre les genoux. Remonte en poussant dans les talons.',
                ['genoux', 'hanches']),
            self::ex('Kettlebell swing', 'kettlebell-swing', 'force', 'corps_entier', 'kettlebell', 'intermediaire', 8.0, 3, 15, null,
                'Balance la kettlebell entre les jambes puis propulse-la à hauteur de poitrine par une extension explosive des hanches. Les bras restent détendus.',
                ['dos', 'hanches', 'epaules']),
            self::ex('Fentes marchées haltères', 'fentes-marchees-halteres', 'force', 'jambes', 'halteres', 'intermediaire', 5.5, 3, 12, null,
                'Haltères le long du corps, avance en fentes en fléchissant les deux genoux à 90°. Garde le buste droit et le pas régulier.',
                ['genoux', 'hanches']),
            self::ex('Marche du fermier', 'marche-du-fermier', 'gainage', 'corps_entier', 'kettlebell', 'intermediaire', 5.0, 3, null, 40,
                'Une charge dans chaque main, marche d’un pas régulier en restant grand, épaules basses et ventre serré. Ne penche pas.',
                ['dos', 'poignets']),

            // ------------------------------------------------------------------
            // FORCE — machines, barre de traction, élastiques
            // ------------------------------------------------------------------
            self::ex('Presse à cuisses', 'presse-a-cuisses', 'force', 'jambes', 'machine', 'debutant', 4.5, 3, 12, null,
                'Pieds largeur d’épaules sur la plateforme, descends jusqu’à 90° sans décoller le bas du dos, puis pousse sans verrouiller les genoux.',
                ['genoux', 'dos']),
            self::ex('Leg curl machine', 'leg-curl-machine', 'force', 'jambes', 'machine', 'debutant', 3.5, 3, 12, null,
                'Allongé ou assis selon la machine, fléchis les genoux pour ramener le coussin vers les fesses puis reviens lentement.',
                ['genoux']),
            self::ex('Leg extension machine', 'leg-extension-machine', 'force', 'jambes', 'machine', 'debutant', 3.5, 3, 12, null,
                'Assis, tends les jambes contre le coussin jusqu’à l’horizontale sans à-coup, puis redescends en contrôlant.',
                ['genoux']),
            self::ex('Tirage vertical machine', 'tirage-vertical-machine', 'force', 'dos', 'machine', 'debutant', 4.5, 3, 12, null,
                'Assis, tire la barre vers le haut de la poitrine en abaissant les coudes et en serrant les omoplates. Remonte lentement.',
                ['epaules', 'coudes']),
            self::ex('Tirage horizontal machine', 'tirage-horizontal-machine', 'force', 'dos', 'machine', 'debutant', 4.5, 3, 12, null,
                'Assis, dos droit, tire la poignée vers le ventre en gardant les coudes près du corps. Reviens en tendant les bras sans arrondir le dos.',
                ['dos', 'coudes']),
            self::ex('Développé assis machine', 'developpe-assis-machine', 'force', 'pectoraux', 'machine', 'debutant', 4.5, 3, 12, null,
                'Assis, poignées au niveau de la poitrine, pousse vers l’avant jusqu’à tendre les bras puis reviens lentement.',
                ['epaules']),
            self::ex('Développé épaules machine', 'developpe-epaules-machine', 'force', 'epaules', 'machine', 'debutant', 4.5, 3, 12, null,
                'Assis, poignées à hauteur d’épaules, pousse au-dessus de la tête sans cambrer. Redescends jusqu’aux oreilles.',
                ['epaules', 'cou']),
            self::ex('Tractions', 'tractions', 'force', 'dos', 'barre_traction', 'avance', 6.5, 4, 6, null,
                'Suspendu à la barre en prise pronation, tire-toi jusqu’à passer le menton au-dessus de la barre en serrant les omoplates. Redescends en contrôlant.',
                ['epaules', 'coudes']),
            self::ex('Tractions australiennes', 'tractions-australiennes', 'force', 'dos', 'barre_traction', 'intermediaire', 5.0, 3, 10, null,
                'Barre basse, corps incliné sous la barre et gainé, tire la poitrine vers la barre puis redescends lentement.',
                ['epaules', 'coudes']),
            self::ex('Suspension à la barre', 'suspension-barre', 'gainage', 'dos', 'barre_traction', 'debutant', 3.0, 3, null, 20,
                'Suspends-toi à la barre bras tendus, épaules actives (légèrement tirées vers le bas), et tiens la position en respirant.',
                ['epaules', 'poignets']),
            self::ex('Squat élastique', 'squat-elastique', 'force', 'jambes', 'elastiques', 'debutant', 4.5, 3, 15, null,
                'Élastique sous les pieds et sur les épaules, descends en squat puis remonte contre la résistance. Genoux dans l’axe des pieds.',
                ['genoux', 'hanches']),
            self::ex('Rowing élastique', 'rowing-elastique', 'force', 'dos', 'elastiques', 'debutant', 4.0, 3, 15, null,
                'Assis jambes tendues, élastique autour des pieds, tire les poignées vers le ventre en serrant les omoplates. Reviens lentement.',
                ['dos', 'coudes']),
            self::ex('Face pull élastique', 'face-pull-elastique', 'force', 'epaules', 'elastiques', 'debutant', 3.5, 3, 15, null,
                'Élastique fixé à hauteur du visage, tire vers toi en écartant les mains au niveau des oreilles, coudes hauts. Reviens en contrôlant.',
                ['epaules']),
            self::ex('Curl biceps élastique', 'curl-biceps-elastique', 'force', 'bras', 'elastiques', 'debutant', 3.0, 3, 15, null,
                'Élastique sous les pieds, coudes collés au corps, fléchis les bras pour amener les poignées vers les épaules. Redescends lentement.',
                ['coudes']),
            self::ex('Extension triceps élastique', 'extension-triceps-elastique', 'force', 'bras', 'elastiques', 'debutant', 3.0, 3, 15, null,
                'Élastique fixé en hauteur, coudes près du corps, tends les avant-bras vers le bas puis reviens sans bouger les coudes.',
                ['coudes']),
            self::ex('Abduction de hanche élastique', 'abduction-hanche-elastique', 'force', 'fessiers', 'elastiques', 'debutant', 3.0, 3, 15, null,
                'Élastique autour des chevilles ou des genoux, écarte une jambe sur le côté sans pencher le buste. Reviens lentement.',
                ['hanches']),
            self::ex('Pont fessier élastique', 'pont-fessier-elastique', 'force', 'fessiers', 'elastiques', 'debutant', 3.5, 3, 15, null,
                'Élastique au-dessus des genoux, allongé sur le dos, monte le bassin en poussant les genoux vers l’extérieur. Redescends sans toucher le sol.',
                ['cou']),
            self::ex('Développé élastique', 'developpe-elastique', 'force', 'pectoraux', 'elastiques', 'debutant', 3.5, 3, 15, null,
                'Élastique passé dans le dos, pousse les poignées vers l’avant jusqu’à tendre les bras, puis reviens en contrôlant.',
                ['epaules']),

            // ------------------------------------------------------------------
            // CARDIO
            // ------------------------------------------------------------------
            self::ex('Jumping jacks', 'jumping-jacks', 'cardio', 'cardio', 'aucun', 'debutant', 8.0, null, null, 40,
                'Saute en écartant les jambes et en levant les bras au-dessus de la tête, puis reviens pieds joints. Garde un rythme régulier.',
                ['genoux', 'chevilles']),
            self::ex('Montées de genoux', 'montees-de-genoux', 'cardio', 'cardio', 'aucun', 'debutant', 8.0, null, null, 40,
                'Cours sur place en montant les genoux à hauteur des hanches, buste droit, bras qui accompagnent. Adapte la vitesse à ton souffle.',
                ['genoux', 'chevilles', 'hanches']),
            self::ex('Talons-fesses', 'talons-fesses', 'cardio', 'cardio', 'aucun', 'debutant', 7.0, null, null, 40,
                'Cours sur place en ramenant les talons vers les fesses, buste droit. Reste léger sur l’avant du pied.',
                ['genoux', 'chevilles']),
            self::ex('Pas chassés', 'pas-chasses', 'cardio', 'cardio', 'aucun', 'debutant', 6.0, null, null, 40,
                'Déplace-toi latéralement en petits sauts, genoux fléchis, puis change de sens. Reste bas et dynamique.',
                ['genoux', 'chevilles']),
            self::ex('Marche sur place', 'marche-sur-place', 'cardio', 'cardio', 'aucun', 'debutant', 3.0, null, null, 60,
                'Marche sur place en levant bien les genoux et en balançant les bras. Idéal pour s’échauffer en douceur.',
                []),
            self::ex('Step touch', 'step-touch', 'cardio', 'cardio', 'aucun', 'debutant', 4.0, null, null, 60,
                'Fais un pas sur le côté et ramène l’autre pied, puis repars dans l’autre sens en rythme. Ajoute les bras pour monter le cœur.',
                []),
            self::ex('Mountain climbers', 'mountain-climbers', 'cardio', 'corps_entier', 'aucun', 'intermediaire', 8.0, null, null, 40,
                'En position de planche sur les mains, ramène alternativement un genou vers la poitrine à un rythme soutenu. Garde le bassin stable.',
                ['poignets', 'epaules', 'hanches']),
            self::ex('Burpees', 'burpees', 'cardio', 'corps_entier', 'aucun', 'avance', 10.0, 3, 10, null,
                'Descends en squat, pose les mains au sol, lance les pieds en arrière en planche, fais une pompe, reviens en squat et saute bras levés.',
                ['genoux', 'poignets', 'epaules', 'chevilles', 'dos']),
            self::ex('Corde à sauter', 'corde-a-sauter', 'cardio', 'cardio', 'aucun', 'intermediaire', 10.0, null, null, 60,
                'Saute à petits bonds sur l’avant des pieds, coudes près du corps, la corde tourne grâce aux poignets. Reste souple à la réception.',
                ['genoux', 'chevilles']),
            self::ex('Shadow boxing', 'shadow-boxing', 'cardio', 'corps_entier', 'aucun', 'debutant', 7.0, null, null, 60,
                'En garde, enchaîne directs et crochets dans le vide en te déplaçant sur les appuis. Garde les épaules relâchées et le ventre serré.',
                ['epaules']),
            self::ex('Course sur tapis', 'course-tapis', 'cardio', 'cardio', 'tapis', 'intermediaire', 9.0, null, null, 600,
                'Cours à une allure où tu peux encore prononcer quelques mots. Regarde devant toi, foulée légère, bras détendus.',
                ['genoux', 'chevilles', 'hanches']),
            self::ex('Marche rapide sur tapis', 'marche-rapide-tapis', 'cardio', 'cardio', 'tapis', 'debutant', 4.5, null, null, 600,
                'Marche d’un bon pas (5–6 km/h) en balançant les bras, sans tenir les poignées. Redresse-toi et regarde loin.',
                []),
            self::ex('Marche inclinée sur tapis', 'marche-inclinee-tapis', 'cardio', 'cardio', 'tapis', 'debutant', 6.0, null, null, 600,
                'Règle une pente de 6 à 10 % et marche d’un pas régulier sans te tenir. Les mollets et les fessiers travaillent davantage.',
                ['chevilles']),
            self::ex('Vélo d’appartement', 'velo-appartement', 'cardio', 'cardio', 'velo', 'debutant', 6.5, null, null, 600,
                'Selle à hauteur de hanche, pédale à une cadence régulière (80–90 tr/min) avec une résistance qui te laisse parler.',
                []),
            self::ex('Fractionné vélo', 'fractionne-velo', 'cardio', 'cardio', 'velo', 'intermediaire', 8.5, null, null, 480,
                'Alterne 30 secondes rapides avec résistance et 60 secondes de récupération souple. Reste assis et garde le haut du corps stable.',
                ['genoux']),

            // ------------------------------------------------------------------
            // GAINAGE
            // ------------------------------------------------------------------
            self::ex('Planche', 'planche', 'gainage', 'abdos', 'aucun', 'debutant', 3.0, 3, null, 30,
                'En appui sur les avant-bras et les pointes de pieds, aligne épaules, bassin et talons. Serre le ventre et les fessiers, respire.',
                ['epaules', 'poignets', 'dos']),
            self::ex('Planche latérale', 'planche-laterale', 'gainage', 'abdos', 'aucun', 'intermediaire', 3.0, 3, null, 20,
                'Sur le côté, en appui sur l’avant-bras et le bord du pied, décolle le bassin pour aligner le corps. Tiens puis change de côté.',
                ['epaules', 'hanches']),
            self::ex('Planche avec toucher d’épaule', 'planche-toucher-epaule', 'gainage', 'abdos', 'aucun', 'intermediaire', 3.5, 3, 12, null,
                'En planche sur les mains, touche l’épaule opposée avec une main en gardant le bassin immobile, puis alterne.',
                ['poignets', 'epaules']),
            self::ex('Hollow hold', 'hollow-hold', 'gainage', 'abdos', 'aucun', 'intermediaire', 3.0, 3, null, 20,
                'Sur le dos, bras tendus derrière la tête et jambes tendues, décolle épaules et jambes en plaquant le bas du dos au sol. Tiens la position.',
                ['dos', 'cou']),
            self::ex('Dead bug', 'dead-bug', 'gainage', 'abdos', 'aucun', 'debutant', 2.5, 3, 10, null,
                'Sur le dos, bras vers le plafond et genoux à 90°, étends lentement un bras et la jambe opposée sans décoller le bas du dos. Alterne.',
                ['cou']),
            self::ex('Bird dog', 'bird-dog', 'gainage', 'dos', 'aucun', 'debutant', 2.5, 3, 10, null,
                'À quatre pattes, tends simultanément un bras devant et la jambe opposée derrière sans bouger le bassin. Reviens et alterne.',
                ['poignets', 'genoux']),
            self::ex('Planche inversée', 'planche-inversee', 'gainage', 'dos', 'aucun', 'intermediaire', 3.0, 3, null, 20,
                'Assis, mains au sol derrière toi doigts vers les pieds, soulève le bassin jusqu’à aligner le corps. Regarde le plafond et serre les fessiers.',
                ['epaules', 'poignets', 'dos']),
            self::ex('Pallof press élastique', 'pallof-press-elastique', 'gainage', 'abdos', 'elastiques', 'intermediaire', 3.0, 3, 10, null,
                'Élastique fixé sur le côté à hauteur de poitrine, tends les bras devant toi puis reviens sans laisser le buste tourner. Change de côté.',
                ['epaules']),

            // ------------------------------------------------------------------
            // MOBILITÉ
            // ------------------------------------------------------------------
            self::ex('Chat-vache', 'chat-vache', 'mobilite', 'mobilite', 'aucun', 'debutant', 2.5, null, null, 60,
                'À quatre pattes, arrondis le dos en rentrant le menton (chat) puis creuse-le en regardant devant (vache). Enchaîne lentement avec la respiration.',
                ['poignets', 'genoux']),
            self::ex('Cercles de bras', 'cercles-de-bras', 'mobilite', 'mobilite', 'aucun', 'debutant', 2.5, null, null, 40,
                'Debout, fais de grands cercles avec les bras vers l’avant puis vers l’arrière, en augmentant progressivement l’amplitude.',
                ['epaules']),
            self::ex('Rotations du bassin', 'rotations-bassin', 'mobilite', 'mobilite', 'aucun', 'debutant', 2.5, null, null, 40,
                'Mains sur les hanches, dessine de grands cercles avec le bassin dans un sens puis dans l’autre. Garde les genoux souples.',
                []),
            self::ex('Rotation thoracique à quatre pattes', 'rotation-thoracique', 'mobilite', 'mobilite', 'aucun', 'debutant', 2.5, 3, 8, null,
                'À quatre pattes, une main derrière la tête, ouvre le coude vers le plafond en tournant le haut du dos, puis reviens. Alterne les côtés.',
                ['poignets', 'genoux', 'dos']),
            self::ex('Fente avec rotation du buste', 'fente-rotation-buste', 'mobilite', 'mobilite', 'aucun', 'intermediaire', 3.0, 3, 8, null,
                'En fente avant basse, tourne le buste vers la jambe avant en ouvrant les bras, puis reviens. Alterne les côtés.',
                ['genoux', 'dos']),
            self::ex('Le plus grand étirement du monde', 'plus-grand-etirement-du-monde', 'mobilite', 'corps_entier', 'aucun', 'intermediaire', 3.0, 3, 6, null,
                'Depuis une fente, pose la main opposée au sol, tourne le buste et lève l’autre bras vers le plafond, puis reviens. Alterne.',
                ['poignets', 'genoux', 'dos']),
            self::ex('Ouverture de hanches 90/90', 'ouverture-hanches-90-90', 'mobilite', 'mobilite', 'aucun', 'intermediaire', 2.5, null, null, 60,
                'Assis, une jambe pliée devant à 90° et l’autre sur le côté à 90°. Penche le buste vers la jambe avant, dos long, puis change de côté.',
                ['hanches', 'genoux']),
            self::ex('Balancements de jambes', 'balancements-de-jambes', 'mobilite', 'mobilite', 'aucun', 'debutant', 3.0, null, null, 40,
                'Tiens-toi à un support et balance une jambe d’avant en arrière en amplitude croissante, puis latéralement. Change de jambe.',
                ['hanches']),
            self::ex('Étirement des ischio-jambiers', 'etirement-ischios', 'mobilite', 'mobilite', 'aucun', 'debutant', 2.5, null, null, 40,
                'Une jambe tendue devant, talon au sol, penche le buste vers l’avant dos plat jusqu’à sentir l’arrière de la cuisse. Respire, puis change.',
                ['dos']),
            self::ex('Étirement des quadriceps debout', 'etirement-quadriceps', 'mobilite', 'mobilite', 'aucun', 'debutant', 2.5, null, null, 40,
                'Debout, attrape un pied derrière toi et ramène le talon vers la fesse, genoux proches. Tiens-toi à un mur si besoin, puis change.',
                ['genoux']),
            self::ex('Étirement du psoas', 'etirement-psoas', 'mobilite', 'mobilite', 'aucun', 'debutant', 2.5, null, null, 40,
                'Genou arrière au sol en fente, avance le bassin vers l’avant en gardant le buste droit jusqu’à sentir l’avant de la hanche. Change de côté.',
                ['genoux', 'hanches']),
            self::ex('Étirement des mollets au mur', 'etirement-mollets', 'mobilite', 'mobilite', 'aucun', 'debutant', 2.5, null, null, 40,
                'Mains au mur, une jambe tendue en arrière talon au sol, avance le bassin jusqu’à sentir le mollet. Tiens puis change de jambe.',
                ['chevilles']),
            self::ex('Étirement des pectoraux au mur', 'etirement-pectoraux-mur', 'mobilite', 'mobilite', 'aucun', 'debutant', 2.5, null, null, 40,
                'Avant-bras contre un mur ou un cadre de porte, coude à hauteur d’épaule, tourne doucement le buste dans l’autre sens. Change de côté.',
                ['epaules']),
            self::ex('Mobilité des chevilles', 'mobilite-chevilles', 'mobilite', 'mobilite', 'aucun', 'debutant', 2.5, null, null, 40,
                'En fente courte, avance le genou vers l’avant au-dessus du pied sans décoller le talon, puis reviens. Fais aussi des cercles de chevilles.',
                []),
            self::ex('Cercles de poignets et chevilles', 'cercles-poignets-chevilles', 'mobilite', 'mobilite', 'aucun', 'debutant', 2.5, null, null, 40,
                'Dessine des cercles lents avec les poignets dans les deux sens, puis avec chaque cheville. Idéal avant les appuis au sol.',
                []),
            self::ex('Posture de l’enfant', 'posture-enfant', 'mobilite', 'mobilite', 'aucun', 'debutant', 2.5, null, null, 60,
                'À genoux, assieds-toi sur les talons et allonge les bras devant toi, front vers le sol. Respire profondément et relâche le dos.',
                ['genoux']),
        ];
    }
}
